---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "Panel de control"
subtitle: "Homer"
logo: "assets/icons/vibrant.png"

header: true
footer: false
columns: 2
connectivityCheck: true

stylesheet:
  - "assets/css/custom.css"

# Nord Theme based on https://pastebin.com/AH9NWmSL
theme: default
colors:
  light:
    highlight-primary: "#323946"
    highlight-secondary: "#323946"
    highlight-hover: "#323946"
    background: "#2E3440"
    card-background: "#323946"
    text: "#81A1C1"
    text-header: "#81A1C1"
    text-title: "#D8DEE9"
    text-subtitle: "#ECEFF4"
    status-offline: "#BF616A"
    status-online: "#A3BE8C"

  dark:
    highlight-primary: "#323946"
    highlight-secondary: "#323946"
    highlight-hover: "#323946"
    background: "#2E3440"
    card-background: "#323946"
    text: "#81A1C1"
    text-header: "#81A1C1"
    text-title: "#D8DEE9"
    text-subtitle: "#ECEFF4"
    status-offline: "#BF616A"
    status-online: "#A3BE8C"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Servicios"
    icon: "fas fa-stream"
    items:
      - name: "Bitwarden"
        subtitle: "Gestor de contraseñas"
        logo: "assets/icons/vaultwarden.png"
        url: "https://contras.local"
        target: "_blank"

  - name: "Sistema"
    icon: "fas fa-cog"
    items:
      - name: "PiHole"
        subtitle: "Servidor DNS local y bloqueador de anuncios y malware"
        logo: "assets/icons/pihole.png"
        url: "https://pihole.local"
        target: "_blank"
