---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "Panel de control"
subtitle: "Homer"
logo: "assets/icons/vibrant.png"

header: true
footer: false
columns: 2
connectivityCheck: false

stylesheet:
  - "assets/css/custom.css"

# Nord Theme based on https://pastebin.com/AH9NWmSL
theme: default
colors:
  light:
    highlight-primary: "#323946"
    highlight-secondary: "#323946"
    highlight-hover: "#323946"
    background: "#2E3440"
    card-background: "#323946"
    text: "#81A1C1"
    text-header: "#81A1C1"
    text-title: "#D8DEE9"
    text-subtitle: "#ECEFF4"
    status-offline: "#BF616A"
    status-online: "#A3BE8C"

  dark:
    highlight-primary: "#323946"
    highlight-secondary: "#323946"
    highlight-hover: "#323946"
    background: "#2E3440"
    card-background: "#323946"
    text: "#81A1C1"
    text-header: "#81A1C1"
    text-title: "#D8DEE9"
    text-subtitle: "#ECEFF4"
    status-offline: "#BF616A"
    status-online: "#A3BE8C"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Servicios"
    icon: "fas fa-stream"
    items:
      - name: "Vaultwarden"
        subtitle: "Gestor de contraseñas"
        logo: "assets/icons/vaultwarden.png"
        url: "https://vault.box"
        target: "_blank"
      # - name: "Openbooks"
      #   subtitle: "Ebooks"
      #   logo: "assets/icons/openbooks.png"
      #   url: "https://openbooks.box"
      #   target: "_blank"
      - name: "Wallabag"
        subtitle: "Lista de leer más tarde/artículos guardados"
        logo: "assets/icons/wallabag.png"
        url: "https://wallabag.box"
        target: "_blank"
      - name: "Memos"
        subtitle: "Registro de notas, cosas que recordar"
        logo: "assets/icons/memos.png"
        url: "https://memos.box"
      - name: "Radicale"
        subtitle: "Servidor de sincronización CalDAV"
        logo: "assets/icons/radicale.svg"
        url: "https://radicale.box"
      - name: "Nextcloud"
        subtitle: "Nube privada"
        logo: "assets/icons/nextcloud.svg"
        url: "https://cloud.box"
      - name: "Photoprism"
        subtitle: "Visor de fotos aumentado con visión artificial"
        logo: "assets/icons/photoprism.svg",
        url: "https://photos.box"

  - name: "Sistema"
    icon: "fas fa-cog"
    items:
      - name: "PiHole"
        subtitle: "Servidor DNS local y bloqueador de anuncios y malware"
        logo: "assets/icons/pihole.png"
        url: "https://pihole.box/admin"
        target: "_blank"
